export default () => ({
    nodes: [
      {
        id: "circle1",
        label: "手机(1.1)",
        deviceName: "手机",
        deviceType: 5,
        comboId: '1',
        comboName: "a区",
        deviceData: {
          name: "手机1",
          ip: "192.168.1.1",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle2",
        label: "手机(1.2)",
        deviceName: "手机",
        deviceType: 5,
        comboId: '1',
        comboName: "a区",
        deviceData: {
          name: "手机2",
          ip: "192.168.1.2",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle3",
        label: "打印机(1.3)",
        deviceName: "打印机",
        deviceType: 6,
        comboId: '1',
        comboName: "a区",
        deviceData: {
          name: "打印机3",
          ip: "192.168.1.3",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle4",
        label: "电脑(1.4)",
        deviceName: "电脑",
        deviceType: 7,
        comboId: '1',
        comboName: "a区",
        deviceData: {
          name: "电脑4",
          ip: "192.168.1.4",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle5",
        label: "电脑(1.5)",
        deviceType: 7,
        deviceName: "电脑",
        comboId: '1',
        comboName: "a区",
        deviceData: {
          name: "电脑5",
          ip: "192.168.1.5",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle6",
        label: "电脑(1.6)",
        deviceName: "电脑",
        deviceType: 8,
        comboId: '2',
        comboName: "b区",
        deviceData: {
          name: "电脑6",
          ip: "192.168.1.6",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle7",
        label: "电脑(1.7)",
        deviceName: "电脑",
        deviceType: 8,
        comboId: '2',
        comboName: "b区",
        deviceData: {
          name: "电脑7",
          ip: "192.168.1.7",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle8",
        label: "手机(1.8)",
        deviceName: "手机",
        deviceType: 9,
        comboId: '2',
        comboName: "b区",
        deviceData: {
          name: "手机8",
          ip: "192.168.1.8",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle9",
        label: "电脑(1.9)",
        deviceName: "电脑",
        deviceType: 8,
        comboId: '2',
        comboName: "b区",
        deviceData: {
          name: "电脑9",
          ip: "192.168.1.9",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle10",
        label: "电脑(1.10)",
        deviceName: "电脑",
        deviceType: 8,
        comboId: '1',
        comboName: "a区",
        deviceData: {
          name: "电脑10",
          ip: "192.168.1.10",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle11",
        label: "手机(1.11)",
        deviceType: 9,
        deviceName: "手机",
        comboId: '2',
        comboName: "b区",
        deviceData: {
          name: "手机11",
          ip: "192.168.1.11",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle12",
        label: "手机(1.12)",
        deviceType: 9,
        deviceName: "手机",
        comboId: '2',
        comboName: "b区",
        deviceData: {
          name: "手机12",
          ip: "192.168.1.12",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle13",
        label: "电脑(1.13)",
        deviceType: 8,
        deviceName: "电脑",
        comboId: '2',
        comboName: "b区",
        deviceData: {
          name: "电脑13",
          ip: "192.168.1.13",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle14",
        label: "电脑(1.14)",
        deviceName: "电脑",
        deviceType: 10,
        comboId: '3',
        comboName: "c区",
        deviceData: {
          name: "电脑14",
          ip: "192.168.1.14",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle15",
        label: "手机(1.15)",
        deviceName: "手机",
        deviceType: 11,
        comboId: '3',
        comboName: "c区",
        deviceData: {
          name: "手机15",
          ip: "192.168.1.15",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle16",
        label: "手机(1.16)",
        deviceName: "手机",
        deviceType: 11,
        comboId: '3',
        comboName: "c区",
        deviceData: {
          name: "手机16",
          ip: "192.168.1.16",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle17",
        label: "打印机(1.17)",
        deviceName: "打印机",
        deviceType: 12,
        comboId: '4',
        comboName: "d区",
        deviceData: {
          name: "打印机17",
          ip: "192.168.1.17",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
      {
        id: "circle18",
        label: "电脑(1.18)",
        deviceName: "电脑",
        deviceType: 13,
        comboName: "d区",
        comboId: '4',
        deviceData: {
          name: "电脑18",
          ip: "192.168.1.18",
          mac: "4C:20:B8:E3:0B:19",
        },
      },
    ],
    edges: [
      {
        source: "circle6",
        target: "circle1",
      },
      {
        source: "circle1",
        target: "circle6",
      },
      {
        source: "circle15",
        target: "circle14",
      },
      {
        source: "circle15",
        target: "circle16",
      },
      {
        source: "circle15",
        target: "circle17",
      },
      {
        source: "circle16",
        target: "circle7",
      },
      {
        source: "circle13",
        target: "circle17",
      },
    ],
  });
